post/urls.py
from django.urls import path
from .views import HomePageView,DetailPageView

urlpatterns=[

    path("", HomePageView.as_view(),name="Home"),
    path("detail/<int:pk>",DetailPageView.as_view(),name="detail")
]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("post.urls"))
]

post/models.py
from django.db import models

# Create your models here.

class Post(models.Model):

    titulo= models.CharField(max_length= 40)
    descripcion= models.TextField()
    #imagen= models.ImageField(upload_to="media" blank=True, null=True)
    autor= models.ForeignKey("auth.User", on_delete=models.CASCADE,blank=True)
        
    def __str__(self):
        
        return self.titulo 

post/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post

# Create your views here.

class HomePageView(ListView):

    model= Post
    template_name= "home.html"

class DetailPageView(DetailView):

    model=Post
    template_name= "detail.html"

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>{{object.titulo}}</h1>
    <br>
    <p>{{post.descripcion}}</p>



</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Twitter</h1>

    {% for objects in post_list %}

    <p><h1>{{objects.titulo}}</h1></p>
    <p>{{objects.descripcion}}</p>

    <a href="{% url 'detail' objects.pk %}">{{objects.titulo}}</a>

    <hr>

    {% endfor %}
        

</body>
</html>